### ISSUE TITLE
Can we change the min iOS version to 10 or less ?

### ISSUE THREAD

**Issue by priteshrnandgaonkar** [apotocki/boost-iosx#1]
Right now I am not able to use this pod because its min supported platform version for iOS is 12, which is quite high. Is there a  reason for this.

I am getting the following

```
    Flipper-Folly (from `/Users/prit91/fbsource/xplat/sonar/iOS/Podspecs/Flipper-Folly.podspec`) was resolved to 2.6.0, which depends on
      boost-iosx (~> 1.76.0)

Specs satisfying the `boost-iosx (~> 1.76.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by apotocki** [comment]
Let's try! I changed ios.deployment_target to '10' in branch 1.76.0
Could you test it?  `pod 'boost-iosx', :git => 'https://github.com/apotocki/boost-iosx', :branch => '1.76.0'` If it works I'll push the changes into cocoapods repo.
