### ISSUE TITLE
[!] Error installing boost

### ISSUE THREAD

**Issue by ReactNativ** [apotocki/boost-iosx#11]
[!] Error installing boost
Verification checksum was incorrect, expected 6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

**Comment by apotocki** [comment]
You may have noticed the problem with the JFrog boost account. At the time of this comment, it's impossible to download Boost even from the official link on the boost.org site. Please consider verifying the checksum once the Boost team resolves their download problems. (look at https://github.com/boostorg/boost/issues/842)
