### ISSUE TITLE
possibility to get a single boost library

### ISSUE THREAD

**Issue by mesqueeb** [apotocki/boost-iosx#14]
Hey! I am trying to use this as a drop in replacement for another boost library I was consuming. The other one would not build for visionOS, that how I reached this repo!

Thanks for all the hard work. : )

I have many build issues it seems, but I'm not sure yet why. I'm thinking perhaps because this boost is not a single framework but it's split up into several ones.

Is there an option to build it as a single boost.xcframework?

**Comment by apotocki** [comment]
I don't think that's a good idea. Boost is a set of different libraries from different authors. That's why each one corresponds to a different xcframework. We should be aware of which libraries we are using and specify only them when linking.

**Comment by mesqueeb** [comment]
Fair enough!
