### ISSUE TITLE
Armv7 and i386 support

### ISSUE THREAD

**Issue by priteshrnandgaonkar** [apotocki/boost-iosx#3]
Are you planning to add Arm7 and i386 support ? Because when you archive the app, it also builds it in arm7. i386 is the intel architecture for 32 bit simulator

Also in M1 machines simulators are of type arm64 too, so if we can have that then it would be awesome.

**Comment by apotocki** [comment]
The script builds artifacts for the current host machine architecture for macOS, catalyst and ios simulator. So for Intel x64 you will have x64, for M1 - arm64 libraries. But I haven't tested it on i386 machine.
I'm not planning arm7 for the same reason - no hardware to test
