### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by timeinpixels** [apotocki/boost-iosx#4]
Is it possible to use the script to build the Apple Silicon version (M1)?

**Comment by apotocki** [comment]
yes

**Comment by daviscdev** [comment]
How can I do this in the script?
I would like to generate a XCFramework containing both x86 and arm64 for iOS simulator to support iOS simulator on M1 Mac.
Expecting result something like ios-arm64_x86_64-simulator or ios-arm64-simulator, ios-x86_64-simulator.
Thanks.

**Comment by apotocki** [comment]
You don't need x86 on M1 Mac and don't need arm64 on x86 Mac, so there is no need to have binaries for both platforms in the same XCFramework. Just run the script on the target platform and it will build the required (only for the current platform) binaries.

**Comment by timeinpixels** [comment]
But if you deploy your app you want to make an universal app so that it runs on both intel and Apple silicon.

**Comment by apotocki** [comment]
What is the purpose of deploying an app built for iOS simulator on another machine? iOS simulator is a tool helping us during the development on a particular development machine. So I really don't see the case where it's worth having a universal binary for simulator.

**Comment by snyuryev** [comment]
The same question - how to build x86_64 simulator on Apple Silicon?

**Comment by apotocki** [comment]
Тот же встречный вопрос - Зачем!?

**Comment by snyuryev** [comment]
@apotocki например как вариант - собирается свой фреймворк, который должен работать на всех архитектурах.

**Comment by apotocki** [comment]
фреймворк будет распространяться в виде бинарников?

**Comment by snyuryev** [comment]
да

**Comment by apotocki** [comment]
Подобный подход не входит в моё понимание **правильного** распространения фреймворков. Поэтому реализации запрашиваемой кросскомпиляции пока не планируется. Однако, я рассмотрю pull request с соответствующей функциональностью, если такой появится.

**Comment by mamunabcoder** [comment]
I have tried to build the boost library but still it's not build for iOS, Can please help me to build this library?

it's urgent to me to build the boost library.

Even CocoaPods not install found some error to install pod

**Comment by apotocki** [comment]
Hi @mamunabcoder! 
Could you provide an installation log?  (at least from the start of "pod install" until the first errors)

**Comment by apotocki** [comment]
now the script builds both x86 and arm64 libs for the iOS simulator and catalyst (1.79.0.3)
